[2024-07-31T10:59:23.294+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T10:59:23.308+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_subprocess_test.dbt_run manual__2024-07-31T03:59:20.827235+00:00 [queued]>
[2024-07-31T10:59:23.314+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_subprocess_test.dbt_run manual__2024-07-31T03:59:20.827235+00:00 [queued]>
[2024-07-31T10:59:23.315+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-31T10:59:23.329+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dbt_run> on 2024-07-31 03:59:20.827235+00:00
[2024-07-31T10:59:23.331+0700] {standard_task_runner.py:64} INFO - Started process 13448 to run task
[2024-07-31T10:59:23.335+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_subprocess_test', 'dbt_run', 'manual__2024-07-31T03:59:20.827235+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dbt_subprocess_test.py', '--cfg-path', '/tmp/tmpexrikbj7']
[2024-07-31T10:59:23.336+0700] {standard_task_runner.py:91} INFO - Job 46: Subtask dbt_run
[2024-07-31T10:59:23.366+0700] {task_command.py:426} INFO - Running <TaskInstance: dbt_subprocess_test.dbt_run manual__2024-07-31T03:59:20.827235+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-07-31T10:59:23.420+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_subprocess_test' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-31T03:59:20.827235+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-31T03:59:20.827235+00:00'
[2024-07-31T10:59:23.421+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T10:59:23.430+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T10:59:23.430+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/dbt_subprocess_test.py", line 26, in run_dbt_command
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Admin/dbt_supermarket'
[2024-07-31T10:59:23.434+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_subprocess_test, task_id=dbt_run, run_id=manual__2024-07-31T03:59:20.827235+00:00, execution_date=20240731T035920, start_date=20240731T035923, end_date=20240731T035923
[2024-07-31T10:59:23.447+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task dbt_run ([Errno 2] No such file or directory: 'C:/Users/Admin/dbt_supermarket'; 13448)
[2024-07-31T10:59:23.466+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T10:59:23.478+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T10:59:23.478+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
